### PR TITLE
Add energy dispersion unit test

### PR DESCRIPTION
**Pull request by LukasNickel**

### CODE REVIEW

**Comment by HealthyPear** [comment]
For the joy of @MaxNoe 

```
Warning, treated as error:
/home/travis/build/cta-observatory/pyirf/docs/changelog.rst:37:Title underline too short.

`0.1.0 <https://github.com/cta-observatory/pyirf/releases/tag/v0.1.0>`__ (2020-09-16)
-----

Error: Error building sphinx doc
```

**Comment by MaxNoe** [comment]
Working on it :rofl:

**Comment by HealthyPear** [comment]
#### Requirements

- [ ] Merge PR #36

**Comment by MaxNoe** [comment]
@HealthyPear This PR targets #36, so merging this will update #36, not the master branch

**Comment by HealthyPear** [comment]
> @HealthyPear This PR targets #36, so merging this will update #36, not the master branch

Ah sorry I didn't  realize it!

**Review by MaxNoe — APPROVED** [review]
Thanks @LukasNickel

**Pull request merged**
