### PR TITLE
Ignore warnings of  possibly NaN bins in sensitivity

### PR DESCRIPTION
**Pull request by Tobychev**
By putting the multiplications with `rel_sens` into a `errstate` context manager that ignores warnings from the invalid floating point operations the NaNs in  `rel_sens` cause.

### CODE REVIEW

**Comment by Tobychev** [comment]
@maxnoe I have no idea why, but I think something has broken the doctests.

**Comment by maxnoe** [comment]
Seems to just be a download failure, I restarted the docs build

**Review by maxnoe — APPROVED** [review]

**Comment by Tobychev** [comment]
The problem seems to be pretty enduring.

**Comment by maxnoe** [comment]
Should be fixed now... let's try again

**Pull request merged**
