### PR TITLE
Doc cuts and bump version

### PR DESCRIPTION
**Pull request by MaxNoe**
The recent PRs made breaking changes, so I bumped the version number as well.

### CODE REVIEW

**Comment by HealthyPear** [comment]
If it's not too much work you could use this PR to update the changelog with the PR merged for 0.2.0, since we increased the versioning.

I had a tool to create an automatic changelog in protopipe, but I forgot the name.
I left a release template in `docs/changelog.rst `than can be simply filled with the PR listed

**Comment by MaxNoe** [comment]
This is how you can get all merges since a specific release:

```
❯ git log --merges --first-parent master --oneline  master...v0.2.0
e406cbe (origin/master, origin/HEAD, master) Merge pull request #67 from cta-observatory/integrate_sim_events
bc826fa Merge pull request #63 from cta-observatory/ogadf
a0e2a24 Merge pull request #61 from cta-observatory/png
f04cdad Merge pull request #58 from cta-observatory/background
edc3068 Merge pull request #60 from cta-observatory/version
0dbec93 Merge pull request #52 from cta-observatory/docs_cov
135fa1f Merge pull request #46 from cta-observatory/travis
```

**Comment by MaxNoe** [comment]
I think writing a changelog for `0.1 → 0.2` does not make too much sense, as it was basically a rewrite.

I would say making a changelog for `0.2 → 0.3` makes sense at the end of the week, right? Or do we want to release a version in between the sprint?

**Comment by HealthyPear** [comment]
> This is how you can get all merges since a specific release:
> 
> ```
> ❯ git log --merges --first-parent master --oneline  master...v0.2.0
> e406cbe (origin/master, origin/HEAD, master) Merge pull request #67 from cta-observatory/integrate_sim_events
> bc826fa Merge pull request #63 from cta-observatory/ogadf
> a0e2a24 Merge pull request #61 from cta-observatory/png
> f04cdad Merge pull request #58 from cta-observatory/background
> edc3068 Merge pull request #60 from cta-observatory/version
> 0dbec93 Merge pull request #52 from cta-observatory/docs_cov
> 135fa1f Merge pull request #46 from cta-observatory/travis
> ```

better add at least the title of the PR (+ the contributor(s))

**Comment by HealthyPear** [comment]
> I think writing a changelog for `0.1 → 0.2` does not make too much sense, as it was basically a rewrite.

Was there only our PR? 

> I would say making a changelog for `0.2 → 0.3` makes sense at the end of the week, right? Or do we want to release a version in between the sprint?

I don't think we are in that kind of hurry now...

**Comment by HealthyPear** [comment]
This is the current build error:

`/home/travis/build/cta-observatory/pyirf/pyirf/cuts.py:docstring of pyirf.cuts.evaluate_binned_cut:17:Unexpected indentation.`

**Review by HealthyPear — APPROVED** [review]

**Pull request merged**
