### PR TITLE
Estimate unique runs taking pointing pos into account

### PR DESCRIPTION
**Pull request by MaxNoe**
This fixes an error of two we had because we assumed that unique `obs_id`s are sufficient for identifying the number of runs.

It is not, as different simulation sets start over with the same run numbers.

We now use unique combinations of `obs_id, pointing_az, pointing_alt`, which should be sufficient at least for the data we currently have. The new data should have the correct histograms, so we won't need that information at all.

### CODE REVIEW

**Comment by MaxNoe** [comment]
Effective area before:
effarea



and after:

effarea2

**Comment by LukasNickel** [comment]
> It is not, as different simulation sets start over with the same run numbers.

That sounds super weird. Any idea why this is done?

**Review by LukasNickel — APPROVED** [review]

**Comment by GernotMaier** [comment]
> > It is not, as different simulation sets start over with the same run numbers.
> 
> That sounds super weird. Any idea why this is done?

Run numbers are limited in CORSIKA: Limit is: 0 ≤ NRRUN ≤ 999999

I don't understand why this matters. We could have the same run number for all runs, as long as we can identify the files in another way.

**Comment by MaxNoe** [comment]
If I remember correctly,. and it is the only thing that makes sense, the CTA data model defines the combination of `OBS_ID, EVENT_ID` to be the unique identifier of an individual event.

This is broken here.

**Comment by GernotMaier** [comment]
You implicitly assume here that CORSIKA run number == OBS_ID. I don't think this is the case.

**Comment by MaxNoe** [comment]
It is at least in this case. Otherwise we wouldn't have had this problem.

**Pull request merged**
