### PR TITLE
Update gammapy requirement to 1.x

### PR DESCRIPTION
**Pull request by maxnoe**

### CODE REVIEW

**Comment by HealthyPear** [comment]
I guess this will unblock #170 ?

**Comment by HealthyPear** [comment]
I think you need to update **setup.py**,

extras_require["all"] = list(set(extras_require["tests"] + extras_require["docs"] **+ extras_require["gammapy"]**))

**Comment by maxnoe** [comment]
Yes, that was inconsistent, but the problem was actually that we need to drop python 3.7 support (NEP29, which gammapy also follows)

**Review by HealthyPear — APPROVED** [review]
For me it's good.

(I removed the superseded `test (3.7)` CI status check)

**Pull request merged**
