### PR TITLE
Doc install for dev

### PR DESCRIPTION
**Pull request by mdpunch**
Modification to docs after discussion on ``fix_gammapy_integration`` branch.
Since this is independent of the gammapy0.19 integration issue, I made a separate branch.

### CODE REVIEW

**Comment by mdpunch** [comment]
But I guess I should have made the branch from the master, instead of from my fix_gammapy_integration branch.

**Review by maxnoe — CHANGES_REQUESTED** [review]
Thanks for this update. It seems you started this branch from your other changes in
#164.

You can fix this by doing removing those commits here. This is a bit more advanced git usage:

Add the `upstream` repository, do an interactive rebase and drop all commits that should not be included here (i.e. the first 4).
```
git remote add upstream git@github.com:cta-observatory/pyirf
git fetch upstream
git rebase -i upstream/master
# edit the file so that you "drop" all commits that don't belong here, save and quit
git push -f
```

**Comment by maxnoe** [comment]
It should look basically like this:

```
drop 03e559a Modified gammapy.py, now working for me with gammapy 0.19
drop 631c2c3 Modified to set gammapy=0.19, fixed FACT example notebook, removed whitespace
drop 9705dc5 Cleared notebook cells
drop 1b6e5be Changed environment.yml from 'gammapy=0.19' to gammapy~=0.19.0'
pick 7e9e022 Modified `Installing for development` according to my understanding from discussion with @maxno

# Rebase ec4c284..7e9e022 onto ec4c284 (5 commands)
#
# Commands:

```

**Comment by mdpunch** [comment]
> git remote add upstream git@github.com:cta-observatory/pyirf

For this, I have ``error: remote upstream already exists.``

**Comment by maxnoe** [comment]
> For this, I have error: remote upstream already exists.

Then you probably already did this earlier and you can just continue with the next command.

An easier variant is also to just make a new branch and cherry pick the relevant commit. 


```
git fetch upstream
git checkout -b update-docs upstream/master 
git cherry-pick 7e9e022
git push -u origin update-docs
```

Then close this and open a new PR from the new branch

**Comment by mdpunch** [comment]
Looking at what's there, I would worry that my change is too conda oriented, in fact.
I'll close this PR and think about it, unless you have suggestions...

**Comment by maxnoe** [comment]
@mdpunch Most people use conda around here, so I don't think that's a problem.

**Pull request closed without merging**
