### PR TITLE
Do not require private DL2 event display output anymore for unit tests

### PR DESCRIPTION
**Pull request by maxnoe**
This will enable contributions from forks again.

### CODE REVIEW

**Review by HealthyPear — APPROVED** [review]

**Review by HealthyPear — CHANGES_REQUESTED** [review]
Sorry I didn't see the CI docs fail: we should install numpydoc

**Comment by HealthyPear** [comment]
> Sorry I didn't see the CI docs fail: we should install numpydoc

Actually it seems all fine: `numpydoc` is one of the docs dependencies and the CI is installing them...

**Comment by HealthyPear** [comment]
Ah I think it's because we are still running the example from `examples/calculate_eventdisplay_irfs.py` in the docs job

**Comment by maxnoe** [comment]
The docs build should be fixed now after rebasing with the current master after the latest PR was merged

**Comment by HealthyPear** [comment]
Either we remove the ED comparison notebook everywhere or we upload a static version

**Comment by maxnoe** [comment]
Done

**Review by HealthyPear — APPROVED** [review]

**Pull request merged**
