### PR TITLE
Add changelog for 0.5.0 release

### PR DESCRIPTION
**Pull request by maxnoe**
@moralejo @jsitarek you might want to be added to the zenodo.json, if yes, please comment with your affiliation and if wanted orcid.

### CODE REVIEW

**Comment by jsitarek** [comment]
Hi @maxnoe 
yes, sure, thx for letting me know

My full affiliation is: University of Lodz, Faculty of Physics and Applied Informatics, Department of Astrophysics
and my Orcid: 0000-0002-1659-5374

**Comment by maxnoe** [comment]
done

**Review by HealthyPear — APPROVED** [review]
Abelardo is missing from the mailmap, but I see that he has 2 commits with only 1 alias, so it should be fine

**Comment by maxnoe** [comment]
@HealthyPear mailmap is only needed to fix someones address.

**Pull request merged**
