### PR TITLE
Add fact example notebook

### PR DESCRIPTION
**Pull request by maxnoe**
Depends on #135, so I make it a draft for now

### CODE REVIEW

**Comment by maxnoe** [comment]
@HealthyPear After merging #135, this is ready for review

**Review by HealthyPear — CHANGES_REQUESTED** [review]
- the CI docs is failing to get the test data, but a local copy works
- the PSF plot is missing a legend
- the energy dispersion plot is missing the axes' labels

**Comment by HealthyPear** [comment]
there aren't OFF observations to use for the bkg rate from this test data I guess

**Comment by maxnoe** [comment]
@HealthyPear there would be a proton file, but the use case is not really there since for wobble observations, you estimate the background from the off regions using something like:
https://docs.gammapy.org/dev/makers/reflected.html

and not the background IRF

**Comment by HealthyPear** [comment]
sure, I meant also real OFF observations, but as you say the use case is more extended than what we have here

**Comment by maxnoe** [comment]
@HealthyPear real off observatins would not be part of the IRF, they are in the DL3 event list from which you select regions for background estimation.

**Comment by maxnoe** [comment]
@HealthyPear Done

**Review by HealthyPear — APPROVED** [review]

**Pull request merged**
