### PR TITLE
added two missing packages that are needed for tests

### PR DESCRIPTION
**Pull request by jsitarek**
PR for  Issue #127

### CODE REVIEW

**Review by maxnoe — APPROVED** [review]

**Comment by maxnoe** [comment]
@jsitarek same story here as in lstchain, for the private test data to be available, PRs have to come from the main repo, not a fork. I pushed your branch to the main repo here: #129

**Comment by jsitarek** [comment]
actually how did you set it such that the tests are running in the main repository despite the need to download the data?
maybe I could also set it up in my fork so the tests would work when I make PR from it. For this one it does not matter because it is very simple, but the other PR already has quite a few files modified, so moving the changes to a separate branch of the main project from my fork might be more tricky

**Comment by maxnoe** [comment]
@jsitarek you just need to push the branch to the correct remote, nothing else is required:

```
git remote add upstream git@github.com:cta-observatory/pyirf
git push upstream interpolate_irfs
```

I tried with setting the secrets also in the fork, but it just doesn't work it seems.

**Comment by HealthyPear** [comment]
> I tried with setting the secrets also in the fork, but it just doesn't work it seems.

It's because it is really not allowed on GitHub
see here https://docs.github.com/en/actions/reference/encrypted-secrets#using-encrypted-secrets-in-a-workflow

**Comment by jsitarek** [comment]
thx @maxnoe @HealthyPear for explanations,

**Pull request closed without merging**
